### ISSUE TITLE
Not working properly in multiplayer

### ISSUE THREAD

**Issue by The1Tead** [blaxxun-boop/Afterdeath#4]
In a multiplayer world the afterdeath system work just fine for me but my friend, instead of spawning as a floating wisp at a skathi statue spawns in the centre of the map in water as a wisp but doesn't float above the water and he must instead swim to the nearest statue to respawn.

**Comment by max-fluff** [comment]
Same, had to disable it. Mod just got recent update. @blaxxun-boop , does it fix this issue?

UPD: No errors in log btw

**Comment by max-fluff** [comment]
My guess is that at `Afterdeath/Afterdeath/Utils.cs:35` FirstOrDefault() returns `null ` but I am not familiar with valheim code base to understand why. Hope it helps!
