### ISSUE TITLE
Antivirus flags afterdeath.dll  in 1.0.3 as infected and moves to quarantine

### ISSUE THREAD

**Issue by Recrimm** [blaxxun-boop/Afterdeath#5]
The infection found on the dll file is Gen:Variant.MSILHeracles.156896

It's on mod version 1.0.3. Mod version 1.0.2 does not have this issue.

![image](https://github.com/user-attachments/assets/915919a1-b7fc-47ef-a466-4f6994737159)

**Comment by blaxxun-boop** [comment]
Then tell your antivirus to shut up.
