### ISSUE TITLE
Bald after revive

### ISSUE THREAD

**Issue by cCaptainn** [blaxxun-boop/Afterdeath#6]
title describes the bug

**Comment by blaxxun-boop** [comment]
No, it does absolutely not. And logs are missing.

**Comment by cCaptainn** [comment]
Yeah, it absolutely does. Why be rude? It's not like I care that much, I just figured you'd want to know. You can check the ping on discord if you want proof, asshole.

**Comment by cCaptainn** [comment]
Yeah, it absolutely does, at least as much as is needed since it's a simple issue with simple reproduction. If you made any effort to reply to other bug reports I might put effort into giving you full reports here. As it stands however, the only time you've replied is when you felt like you could "snap back" at someone so why should I bother giving you any further direction?
